baseURL = 'https://www.hugolhld.github.io/gh_test/'
languageCode = 'fr-FR'
title = 'HL - Hugo.io'
theme = 'ananke'
staticDir = ['static']
sectionPagesMenu = 'main'


DefaultContentLanguage = "fr"

[params]
    description = 'Ouhou'
    site_logo = '/gh_test/img/fav2.png'
    background_color_class = 'bg-blue'
    text_color = 'blue'
    date_format = "2. January 2006"

[[params.ananke_socials]]
    name = "github"
    url = "https://www.github.com/hugolhld"
