baseURL = 'https://www.hugolhld.github.io/gh_test/'
languageCode = 'fr-FR'
title = 'GitHub - Hugo Course'
theme = 'ananke'
staticDir = ['static']


DefaultContentLanguage = "fr"

[params]
    descirption = 'Ouhou'
    background_color_class = 'bg-blue'
    featured_image = '/gh_test/img/bg.jpeg'
    site_logo = '/gh_test/img/bg.jpeg'
    text_color = 'green'
    date_format = "2. January 2006"
